book: 
  chapters:
    - index.qmd
    - part: "Introducing Machine Learning"
      chapters: 
        - source/01-data-and-models.qmd
        - source/02-black-box-classification.qmd
    - part: "Fundamentals of Prediction"
      chapters: 
        - source/03-score-based-classification.qmd 
        - source/04-decision-theory.qmd 
    - part: "Discrimination, Disparity, Data"
      chapters: 
        - source/10-compas.qmd
        - source/12-statistical-fairness.qmd
    - part: "Machine Learning Models"
      chapters:
        - source/20-perceptron.ipynb
        - source/22-convex-erm.ipynb
        - source/23-gradient-descent.ipynb
        - source/30-features-regularization.qmd
        - source/40-linear-regression.ipynb
        - source/50-kernel-methods.ipynb
        - source/51-vectorization.ipynb
    - part: "Deep Learning"
      chapters: 
        - source/60-intro-deep.ipynb