project: 
  pre-render: 
    - scripts/create-ipynb.py
    - scripts/prep-qmd.py

book: 
  chapters:
    - index.qmd
    - part: "Introducing Machine Learning"
      chapters: 
        - chapters/01-data-and-models.qmd
        - chapters/02-black-box-classification.qmd
    - part: "Fundamentals of Prediction"
      chapters: 
        - chapters/03-score-based-classification.qmd 
        - chapters/04-decision-theory.qmd 
    - part: "Discrimination, Disparity, Data"
      chapters: 
        - chapters/10-compas.qmd
        - chapters/12-statistical-fairness.qmd
    - part: "Machine Learning Models"
      chapters: 
        - chapters/20-perceptron.ipynb
        - chapters/22-convex-erm.ipynb 
        - chapters/23-gradient-descent.ipynb
        - chapters/30-features-regularization.qmd
        - chapters/40-linear-regression.ipynb
        - chapters/50-kernel-methods.ipynb
        - chapters/51-vectorization.ipynb