book: 
  chapters:
    - index.qmd
    - part: "Introducing Machine Learning"
      chapters: 
        - source/01-data-and-models.qmd
        - source/02-black-box-classification.qmd
    - part: "Fundamentals of Prediction"
      chapters: 
        - source/03-score-based-classification.qmd 
        - source/04-decision-theory.qmd 
  